version: '3'
services:
    web:
        image: letters-api:dev
        ports:
            - "5001:5001"
        volumes:
            - ./src/letters/:/project/src/letters/
        command: ["uvicorn", "letters.anagrammer.main:app", "--reload", "--host", "0.0.0.0", "--port", "5001"]  
    db:
        ports:
            - "5432:5432"
