version: '3'
services:
    web:
        build: .
        restart: "always"
        ports:
            - "5000:80"
        volumes:
            - .:/var/www/letters-api/
        environment:
            FLASK_ENV: development
        depends_on:
            - "db"
        networks:
            - api-network        
    db:
        image: "postgres"
        restart: "always"
        ports: 
            - "5432:5432"
        environment:
            POSTGRES_DB: words
            POSTGRES_USER: api
            POSTGRES_PASSWORD: letters
        volumes:
            - pgVolume:/var/lib/postgresql/data
            - ./logs/logs # This may involve some permissioning on the folder in the container filesystem
            # https://stackoverflow.com/questions/30848670/how-to-customize-the-configuration-file-of-the-official-postgresql-docker-image/41912295
        networks:
            api-network:
                # The aliases can be used as host names when creating connections
                aliases:
                    - pgLettersApi

# Due to the way Docker works, you can't just refer to localhost. The most sensible way to do this 
# seems to be create a network across the containers. 
networks:
    api-network:
        driver: bridge

# This creates a named volume for persisting data in the postgres db
volumes:
    pgVolume: