FROM python:3.7-slim
WORKDIR /var/www/letters-api/

# Install app requirements
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . /var/www/letters-api/

# Run apache server
EXPOSE 80
CMD ["flask", "run", "--host=0.0.0.0", "--port", "5001"]